random_seed: 0
batch_size: 512
n_epoch: 1000

train_root: 'dataGeneration/E1Data/train/'
val_root: 'dataGeneration/E1Data/val/'
formats: ['.csv']

# Radius model
optimizer_r: 'adam'
lr_r: 1e-5
weight_decay_r: 0
adam_eps_r: 1e-8
adam_amsgrad_r: True

# e1 prediction
optimizer_e1: 'adam'
lr_e1: 1e-5
weight_decay_e1: 0
adam_eps_e1: 1e-8
adam_amsgrad_e1: True

input_key: 'A_abs'

LOSS_WEIGHT_DIR: 'configs/loss_weights/'
