# v7 with weight_decay 1e-3

random_seed: 0
batch_size: 32
n_epoch: 1000

train_root: 'dataGeneration/data/train/'
val_root: 'dataGeneration/data/val/'
formats: ['.csv']

optimizer: 'adam'
lr: 1e-5
weight_decay: 1e-3
adam_eps: 1e-8
adam_amsgrad: True

CHECKPOINT_DIR: 'checkpoints/Basic/'
LOSS_WEIGHT_DIR: 'configs/loss_weights/'

scheduler: 0.95